//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace HotelBooking_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        public int PhoneNumber { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public System.DateTime StartDate { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public System.DateTime EndDate { get; set; }

        [Required]
        public string HotelName { get; set; }

        [Required]
        public int RoomNo { get; set; }

        [Required]
        public string City { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        public int HotelNumber { get; set; }
        //public Nullable<int> CustomerId { get; set; }
        public Nullable<int> HotelId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
